# employee_viz.py
# Contact: 24f2009046@ds.study.iitm.ac.in

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import textwrap

# ---------- Parameters ----------
CSV_FILE = "employee_data.csv"
PNG_FILE = "employee_dept_hist.png"
HTML_FILE = "report.html"
VERIFICATION_EMAIL = "24f2009046@ds.study.iitm.ac.in"
# --------------------------------

def main():
    # 1) Load data
    df = pd.read_csv(CSV_FILE)

    # 2) Frequency counts
    dept_counts = df['department'].value_counts()
    finance_count = dept_counts.get('Finance', 0)

    # Print to console
    print("Department counts:")
    print(dept_counts.to_string())
    print()
    print(f"Frequency count for Finance department: {finance_count}")

    # 3) Create histogram (countplot) of departments using seaborn
    plt.figure(figsize=(10,6))
    sns.set_style("whitegrid")
    ax = sns.countplot(y='department', data=df, order=dept_counts.index)
    ax.set_title("Employee Count by Department")
    ax.set_xlabel("Count")
    ax.set_ylabel("Department")

    # Annotate bars with counts
    for p in ax.patches:
        width = p.get_width()
        ax.text(width + 0.3, p.get_y() + p.get_height() / 2,
                int(width), va='center')

    plt.tight_layout()
    plt.savefig(PNG_FILE, dpi=150)
    plt.close()
    print(f"\nSaved histogram as: {PNG_FILE}")

    # 4) Embed the key code in the HTML
    python_code = textwrap.dedent("""\
    import pandas as pd
    import matplotlib.pyplot as plt
    import seaborn as sns

    df = pd.read_csv("employee_data.csv")

    # Frequency counts
    dept_counts = df['department'].value_counts()
    finance_count = dept_counts.get('Finance', 0)

    print("Department counts:")
    print(dept_counts.to_string())
    print(f"Frequency count for Finance department: {finance_count}")

    # Plot histogram
    plt.figure(figsize=(10,6))
    sns.countplot(y='department', data=df, order=dept_counts.index)
    plt.title("Employee Count by Department")
    plt.xlabel("Count")
    plt.ylabel("Department")
    plt.show()
    """)

    # 5) Create HTML
    html_content = f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Employee Departments Report</title>
  <style>
    body {{ font-family: Arial, sans-serif; max-width:900px; margin:40px; }}
    .header {{ margin-bottom: 20px; }}
    .counts, pre.code {{ background:#f6f6f6; padding:10px; border-radius:6px; }}
    img {{ max-width:100%; height:auto; border:1px solid #ddd; padding:6px; background:white; }}
    footer {{ margin-top:30px; color:#666; font-size:0.9em; }}
  </style>
</head>
<body>
  <div class="header">
    <h1>Employee Departments Report</h1>
    <p>Verification email: <strong>{VERIFICATION_EMAIL}</strong></p>
  </div>

  <h2>Department counts</h2>
  <div class="counts">
    <pre>{dept_counts.to_string()}</pre>
    <p><strong>Finance count: {finance_count}</strong></p>
  </div>

  <h2>Department distribution</h2>
  <img src="{PNG_FILE}" alt="Department histogram">

  <h2>Python code used</h2>
  <pre class="code">{python_code}</pre>

  <footer>Generated by employee_viz.py</footer>
</body>
</html>
"""
    with open(HTML_FILE, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"Saved HTML report as: {HTML_FILE}")
    print("\nTo view the report locally, open:", os.path.abspath(HTML_FILE))

if __name__ == "__main__":
    main()